"""Self-contained HTML report. Requires the ``report`` extra (matplotlib)."""

from __future__ import annotations

import base64
import html
import io

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from evalstats.analysis import leaderboard, summarize

__all__ = ["build_report"]

_CSS = """
body{font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;margin:2rem auto;max-width:60rem;color:#1a1a1a}
h1{margin-bottom:0}.sub{color:#666;margin-top:.25rem}
table{border-collapse:collapse;margin:1rem 0;font-size:14px}
th,td{border:1px solid #ddd;padding:.35rem .6rem;text-align:right}
th{background:#f5f5f5}td:first-child,th:first-child{text-align:left}
tr.sig td{background:#fff3cd}
img{max-width:100%;margin:1rem 0}
code{background:#f2f2f2;padding:.1rem .3rem;border-radius:3px}
"""


def _fig_to_uri(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=120, bbox_inches="tight")
    plt.close(fig)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def _ranking_plot(table: pd.DataFrame):
    fig, ax = plt.subplots(figsize=(7, 0.6 * len(table) + 1))
    y = range(len(table))
    lo = table["mean"] - table["ci_low"]
    hi = table["ci_high"] - table["mean"]
    ax.errorbar(table["mean"], y, xerr=[lo, hi], fmt="o", capsize=4)
    ax.set_yticks(list(y))
    ax.set_yticklabels(table["model"])
    ax.invert_yaxis()
    ax.set_xlabel("overall score (cluster-robust 95% CI)")
    ax.grid(axis="x", alpha=0.3)
    return fig


def build_report(
    df: pd.DataFrame,
    out_path: str,
    *,
    level: float = 0.95,
    correction: str = "holm",
    seed: int = 0,
) -> str:
    summ = summarize(df, level=level, seed=seed)
    table, pairs = leaderboard(df, level=level, correction=correction, seed=seed)

    n_models = df["model"].nunique()
    n_tasks = df["task"].nunique()
    n_items = len(df)
    ranking_uri = _fig_to_uri(_ranking_plot(table))

    def _table_html(frame: pd.DataFrame, sig_col: str | None = None) -> str:
        if sig_col and sig_col in frame.columns:
            rows = []
            for _, r in frame.iterrows():
                cls = ' class="sig"' if bool(r[sig_col]) else ""
                cells = "".join(f"<td>{html.escape(_fmt(v))}</td>" for v in r)
                rows.append(f"<tr{cls}>{cells}</tr>")
            head = "".join(f"<th>{html.escape(c)}</th>" for c in frame.columns)
            return f"<table><thead><tr>{head}</tr></thead><tbody>{''.join(rows)}</tbody></table>"
        return frame.to_html(index=False, border=0, float_format=lambda v: f"{v:.4f}")

    body = f"""<!doctype html><meta charset="utf-8">
<title>evalstats report</title><style>{_CSS}</style>
<h1>evalstats report</h1>
<p class="sub">{n_models} models &middot; {n_tasks} tasks &middot; {n_items} scored items
&middot; {level:.0%} intervals &middot; {html.escape(correction)} correction</p>

<h2>Ranking</h2>
<img alt="ranking" src="{ranking_uri}">
{_table_html(table)}

<h2>Pairwise comparisons</h2>
<p>Highlighted rows are significant after correction (paired sign-flip
randomization test, cluster bootstrap CI). A gap whose CI spans 0 is within noise.</p>
{_table_html(pairs, sig_col="significant")}

<h2>Per-task breakdown</h2>
{_table_html(summ)}

<p class="sub">Methods: Miller (2024), <code>arXiv:2411.00640</code>;
Dror et al. (2018). Generated by evalstats.</p>
"""
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(body)
    return out_path


def _fmt(v) -> str:
    if isinstance(v, float):
        return f"{v:.4f}"
    return str(v)
